[package]
name = "shadertool"
version = "0.1.0"
authors = ["Mees Delzenne <mees.delzenne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.29.0"
notify = "5.0.0-pre.6"
glam = {version = "0.13.0", features=["serde"]}
imgui = "0.7.0"
imgui-glium-renderer = "0.7.0"
imgui-winit-support = "0.7.0"
glutin = "0.26.0"
serde = "1.0.124"
serde_json = "1.0.64"
serde_derive = "1.0.124"
anyhow = "1.0.38"
env_logger = "0.8.3"
log = "0.4.14"
spin_sleep = "1.0.0"
